FROM node:22 AS develop
EXPOSE 3000
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN mkdir -p /root/Downloads /app
WORKDIR /app

COPY package.json /app
COPY pnpm-lock.yaml /app

# Install deps and browsers for playwrite
RUN pnpm install --frozen-lockfile && pnpm playwright install chromium --only-shell --with-deps

# Copy site code
COPY . /app
VOLUME /app

# Command that runs
ENTRYPOINT ["pnpm"]
CMD ["start", "--host", "--no-open"]
