FROM node:22 AS develop
EXPOSE 3000

RUN mkdir -p /root/Downloads /app
WORKDIR /app

COPY package.json /app
COPY pnpm-lock.yaml /app

# Install deps and browsers for playwrite
RUN pnpm install && pnpm playwright install chromium --only-shell --with-deps

# Copy site code
COPY . /app
VOLUME /app

# Command that runs
ENTRYPOINT ["pnpm"]
CMD ["start", "--host", "--no-open"]
