FROM node:22-slim AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app
COPY pnpm-lock.yaml /app

# Install Deps
RUN pnpm install --frozen-lockfile

# Build site
COPY . /app
RUN pnpm build

FROM nginx:alpine
LABEL maintainer="kelsin@valefor.com"
WORKDIR /usr/share/nginx/html

COPY docker/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/site /usr/share/nginx/html
