FROM node:22-slim AS build

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app
COPY pnpm-lock.yaml /app

# Install Deps
RUN pnpm install

# Build site
COPY . /app
RUN pnpm build

FROM nginx:alpine
LABEL maintainer="kelsin@valefor.com"
WORKDIR /usr/share/nginx/html

COPY docker/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html
