FROM node:22 AS develop
EXPOSE 3000

RUN mkdir -p /root/Downloads /app
WORKDIR /app

COPY package.json /app
COPY yarn.lock /app

# Install deps and browsers for playwrite
RUN yarn && yarn playwright install chromium --only-shell --with-deps

# Copy site code
COPY . /app
VOLUME /app

# Command that runs
ENTRYPOINT ["yarn"]
CMD ["start", "--host", "--no-open"]
