on:
  push:
    tags:
      - "*"
jobs:
  app:
    runs-on: macos-latest
    permissions:
      contents: write
    name: Build App
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Node
        with:
          architecture: x64
          check-latest: true
          node-version: 22
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Keys
        run: |
          echo $APP_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security import certificate.p12 -k build.keychain -P $APP_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
        env:
          APP_CERTIFICATE: ${{ secrets.APP_CERTIFICATE }}
          APP_CERTIFICATE_PWD: ${{ secrets.APP_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - run: yarn
        name: Dependencies
      - id: create_release
        name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          name: 18xx Maker ${{ github.ref_name }}
          body: 18xx Maker ${{ github.ref_name }}
          draft: true
          prerelease: true
      - run: yarn release
        name: Build Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          APPLE_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      - uses: StuYarrow/publish-release@v1
        name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
