on:
  push:
    tags:
      - "*"
name: App
jobs:
  app:
    runs-on: macos-latest
    permissions:
      contents: write
    name: Build App
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          architecture: x64
          node-version: 22
          check-latest: true
      - name: Keys
        run: |
          echo $APP_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security import certificate.p12 -k build.keychain -P $APP_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
        env:
          APP_CERTIFICATE: ${{ secrets.APP_CERTIFICATE }}
          APP_CERTIFICATE_PWD: ${{ secrets.APP_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: macos-latest-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Draft
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: 18xx Maker ${{ github.ref_name }}
          body: 18xx Maker ${{ github.ref_name }}
          draft: true
          prerelease: true
      - name: Build
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          APPLE_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      - name: Publish
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
