on:
  push:
    tags:
      - "*"

name: App

jobs:
  app:
    name: App
    runs-on: macos-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Keys
        run: |
          echo $APP_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security import certificate.p12 -k build.keychain -P $APP_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
        env:
          APP_CERTIFICATE: ${{ secrets.APP_CERTIFICATE }}
          APP_CERTIFICATE_PWD: ${{ secrets.APP_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: mac-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Build
        id: build
        run: |
          yarn build:app
          yarn package:app
          {
            echo 'ARTIFACTS<<EOF'
            basename -a out/app/{latest,18xx-maker}*
            echo EOF
          } >> "$GITHUB_ENV"
          echo "### :electron: Created the following artifacts" >> $GITHUB_STEP_SUMMARY
          basename -a out/app/{latest,18xx-maker}* >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          APPLE_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      - name: Upload
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} $(echo ${{ steps.build.outputs.ARTIFACTS }} | xargs) ./README.md ./LICENSE
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-path: ${{ steps.build.outputs.ARTIFACTS }}
