env:
  REGISTRY: ghcr.io
  DOCKER_BUILD_RECORD_UPLOAD: false
on:
  push:
    tags:
      - "*"
name: Docker
jobs:
  docker:
    strategy:
      matrix:
        image: [site, develop]
    name: 18xx-maker/${{ matrix.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: ${{ env.REGISTRY }}/18xx-maker/${{ matrix.image }}
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=18xx-maker/${{ matrix.image }}
          annotations: |
            org.opencontainers.image.title=18xx-maker/${{ matrix.image }}
      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta.outputs.annotations }}
          file: docker/Dockerfile.${{ matrix.image }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=${{ matrix.image }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image }}
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          push-to-registry: true
          subject-digest: ${{ steps.build.outputs.digest }}
          subject-name: ${{ env.REGISTRY }}/18xx-maker/${{ matrix.image }}
