on:
  push:
    tags:
      - "*"
name: Docker
jobs:
  latest:
    runs-on: ubuntu-latest
    name: 18xx:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kelsin/18xx
          tags: |
            type=ref,event=tag
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Readme
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ var.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: kelsin/18xx
          short-description: Prototype 18xx React Library
  develop:
    runs-on: ubuntu-latest
    name: 18xx:develop
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kelsin/18xx
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,value=develop
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.develop
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
