on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 22
        architecture:
          - x64
    name: Test - Node v${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Node
        uses: actions/setup-node@v4
        with:
          architecture: ${{ matrix.architecture }}
          node-version: ${{ matrix.node_version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
        name: Dependencies
      - run: yarn eslint .
        name: Lint
      - run: yarn validate
        name: Validate
      - run: yarn test
        name: Test
      - run: yarn build
        name: Build
