on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 22
        architecture:
          - x64
    name: Test - Node v${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          architecture: ${{ matrix.architecture }}
          node-version: ${{ matrix.node_version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Dependencies
        run: yarn
      - name: Commits
        if: matrix.os == 'ubuntu-latest'
        uses: wagoid/commitlint-github-action@v6
      - name: Pretty
        run: yarn pretty
      - name: Lint
        run: yarn lint
      - name: Validate
        run: yarn validate
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
