on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 22
        architecture:
          - x64
    name: Test - Node v${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.architecture }}
        cache: 'yarn'
    - uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ matrix.os }}-${{ matrix.node_version }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: yarn test
  build:
    runs-on: macos-latest
    name: Build webapp
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
    - uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: macos-latest-22-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: yarn build
