on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
name: Push
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 22
        architecture:
          - x64
    name: Test - Node v${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          architecture: ${{ matrix.architecture }}
          node-version: ${{ matrix.node_version }}
          check-latest: true
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ matrix.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Commits
        if: matrix.os == 'ubuntu-latest'
        uses: wagoid/commitlint-github-action@v6
      - name: Pretty
        run: yarn pretty
      - name: Lint
        run: yarn lint
      - name: Validate
        run: yarn validate
      - name: Test
        run: yarn test
      - name: Upload Coverage - Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Coverage - Codacy
        if: matrix.os == 'ubuntu-latest'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{github.workspace}}/coverage/clover.xml
      - name: Build Web
        run: yarn build
      - name: Build App
        run: yarn build:app
