env:
  PLAYWRIGHT_BROWSERS_PATH: browsers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
name: Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 22
      - name: Commits
        uses: wagoid/commitlint-github-action@v6
        if: github.event_name == 'pull_request'
      - name: Dependencies
        run: pnpm install
      - name: Build Web
        run: pnpm build
      - name: Build App
        run: pnpm build:app
      - name: Summary
        run: "echo :package: Build tests succeeded >> $GITHUB_STEP_SUMMARY"
  test:
    strategy:
      matrix:
        node: [22]
        os:
          - name: Linux
            slug: linux
            image: ubuntu-latest
            emoji: penguin
          - name: Mac
            slug: mac
            image: macos-latest
            emoji: apple
          - name: Windows
            slug: windows
            image: windows-latest
            emoji: window
    name: ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node }}
      - name: Dependencies
        run: pnpm install
      - name: Playwright Version
        id: playwright-version
        shell: bash
        run: echo "PLAYWRIGHT_VERSION=$(pnpm exec playwright --version | awk '{ print $2 }')" >> $GITHUB_OUTPUT
      - name: Playwright Cache
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: browsers
          key: ${{ matrix.os.slug }}-browsers-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
      - name: Playwright Install
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm playwright install chromium --only-shell --with-deps
      - name: Pretty
        run: pnpm pretty
      - name: Lint
        run: pnpm lint
      - name: Validate
        run: pnpm validate
      - name: Test
        run: pnpm test
      - name: Coverage
        uses: coverallsapp/github-action@v2
        if: matrix.os.slug == 'linux'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Summary
        shell: bash
        run: "echo :${{ matrix.os.emoji }}: ${{ matrix.os.name }} tests succeeded >> $GITHUB_STEP_SUMMARY"
