env:
  NODE_VERSION: 22
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
name: Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: linux-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Build Web
        run: yarn build
      - name: Build App
        run: yarn build:app
      - name: Summary
        run: "echo :package: Build tests succeeded >> $GITHUB_STEP_SUMMARY"
  linux:
    name: Linux
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commits
        uses: wagoid/commitlint-github-action@v6
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: linux-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Pretty
        run: yarn pretty
      - name: Lint
        run: yarn lint
      - name: Validate
        run: yarn validate
      - name: Test
        run: yarn test
      - name: Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Summary
        run: "echo :penguin: Linux tests succeeded >> $GITHUB_STEP_SUMMARY"
  mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: mac-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Pretty
        run: yarn pretty
      - name: Lint
        run: yarn lint
      - name: Validate
        run: yarn validate
      - name: Test
        run: yarn test
      - name: Summary
        run: "echo :apple: MacOS tests succeeded >> $GITHUB_STEP_SUMMARY"
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: windows-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        run: yarn --frozen-lockfile
      - name: Pretty
        run: yarn pretty
      - name: Lint
        run: yarn lint
      - name: Validate
        run: yarn validate
      - name: Test
        run: yarn test
      - name: Summary
        run: "echo :window: Windows tests succeeded >> $GITHUB_STEP_SUMMARY"
